include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_if_null_operators
    - prefer_null_aware_operators
